name: Java Organization CI

on:
  workflow_call:
    inputs:
      app_dir:
        description: Set application path to build, leave empty if not needed
        type: string
        default: ./
      java_version:
        description: Set java version used in the build
        type: string
        default: '22'
    # secrets:  # Defines the secrets that can be passed from the caller workflow
    #   envPAT:  # Name of the secret
    #     required: true  # Specifies that this secret is mandatory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone git repository
        uses: actions/checkout@v4.1.6

      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '${{ inputs.java_version }}'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.3.2
        with:
          # gradle-version: 5.6.2
          gradle-version: wrapper

      - name: Run build with Gradle Wrapper
        run: cd ./${{ inputs.app_dir }} && gradle --no-daemon clean build -x test